### ISSUE TITLE
Crash on HA 2026.8: async_device_info_to_link_from_entity now always returns None → 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by wuehler** [wbyoung/lampie#34]
### Requirements

- [x] I have updated Lampie to the latest available version.

- [x] I did a search to see if there is a similar issue or if a pull request is open.

### Summary
On Home Assistant **2026.8+**, activating or dismissing any Lampie notification crashes with `TypeError: 'NoneType' object is not subscriptable`, and the switch service call fails (`Failed to perform the action switch/turn_on...`). Affects the current release, v0.3.0.

### Environment
- Home Assistant Core: **2026.8.1** (HAOS)
- Lampie: **v0.3.0**
- Switches: Inovelli VZM31-SN on ZHA

### Traceback
```
File ".../custom_components/lampie/switch.py", line 135, in async_turn_on
    await self.orchestrator.activate_notification(self.coordinator.slug)
File ".../custom_components/lampie/orchestrator.py", line 916, in _issue_switch_commands
    await self._dispatch_service_command(...)
File ".../custom_components/lampie/orchestrator.py", line 958, in _zha_service_command
    id_tuple = next(iter(device_info["identifiers"]))
TypeError: 'NoneType' object is not subscriptable
```

### Root cause
`_issue_switch_commands` (orchestrator.py:895) does:
```python
device_info = async_device_info_to_link_from_entity(self._hass, switch_id)
```
As of HA 2026.8, `homeassistant.helpers.device.async_device_info_to_link_from_entity` (and `async_device_info_to_link_from_device_id`) are **deprecated and unconditionally return `None`** — part of the "a device belongs to a single config entry" change. The HA source now reads:
```python
def async_device_info_to_link_from_entity(hass, entity_id_or_uuid) -> dr.DeviceInfo | None:
    """Deprecated, always returns None; set entity.device_entry instead."""
    report_usage("...deprecated and always returns None... Set entity.device_entry = "
                 "async_entity_id_to_device(hass, source_entity_id) instead",
                 breaks_in_ha_version="2027.8.0")
    return None
```
So `device_info` is always `None`, and `_zha_service_command` (line 958) then does `device_info["identifiers"]` → crash.

Three call sites use the helper:
- `orchestrator.py:895` (`_issue_switch_commands`) — **unguarded → crash**
- `__init__.py:94` (`async_cleanup_device_registry`) — guarded with `if device_info is not None`
- `sensor.py:161` — guarded

### Suggested fix
`_zha_service_command` only needs the device's ZHA IEEE (its `("zha", <ieee>)` identifier). Resolve it directly instead of via the deprecated helper, e.g.:
```python
ent = er.async_get(self._hass).async_get(switch_id)
dev = dr.async_get(self._hass).async_get(ent.device_id) if ent and ent.device_id else None
device_info = dr.DeviceInfo(identifiers=dev.identifiers, connections=dev.connections) if dev else None
```
For the entity-linking call sites, HA's guidance is to set `entity.device_entry = async_entity_id_to_device(hass, source_entity_id)` instead of passing borrowed identifiers through `device_info`.

### Steps to reproduce
1. HA 2026.8+, one Lampie notification config targeting a ZHA Inovelli switch.
2. Toggle the notification `switch.*` entity on or off.
3. → `Failed to perform the action switch/turn_on. 'NoneType' object is not subscriptable`.

### What version of Lampie has the issue?

v0.3.0

### Anything in the logs that might be useful for us?

```txt

```

**Comment by pkscout** [comment]
I had ChatGPT help me find the problem.  I'm a Python programmer, but I didn't know enough about Lampie or the API changes in HA 2026.8.0 to figure it out on my own.  Here are some instructions to patch.  I have confirmed this fixes the issues for me.  If I have some time, I will put in a PR with the changes.

Lampie v0.3.0 compatibility fix for HA 2026.8

On HA 2026.8.3, Lampie v0.3.0 fails when enabling a notification with:

`TypeError: 'NoneType' object is not subscriptable`

The problem is that async_device_info_to_link_from_entity() is deprecated in HA 2026.8 and now returns None.

A minimal fix is:

1. In custom_components/lampie/orchestrator.py, change the import:

```
from homeassistant.helpers.device import (
    async_device_info_to_link_from_entity,
    async_entity_id_to_device_id,
)
```

to:

```
from homeassistant.helpers.device import async_entity_id_to_device_id
```

2. Around line 895, change:

```
device_info = async_device_info_to_link_from_entity(self._hass, switch_id)
```

to:

```
device_id = async_entity_id_to_device_id(self._hass, switch_id)
device_info = dr.async_get(self._hass).async_get(device_id) if device_id else None
```

3. In _zha_service_command(), change:

```
id_tuple = next(iter(device_info["identifiers"]))
```

to:

```
id_tuple = next(iter(device_info.identifiers))
```

The existing `ieee = id_tuple[1]` line remains unchanged.

This allows Lampie to obtain the DeviceEntry from the entity ID using the current HA API and access its identifiers as attributes rather than using the old DeviceInfo dictionary.

**Comment by pkscout** [comment]
PR submitted.  https://github.com/wbyoung/lampie/pull/35

**Comment by mochman** [comment]
> I had ChatGPT help me find the problem. I'm a Python programmer, but I didn't know enough about Lampie or the API changes in HA 2026.8.0 to figure it out on my own. Here are some instructions to patch. I have confirmed this fixes the issues for me. If I have some time, I will put in a PR with the changes.
> 
> Lampie v0.3.0 compatibility fix for HA 2026.8
> 
> On HA 2026.8.3, Lampie v0.3.0 fails when enabling a notification with:
> 
> `TypeError: 'NoneType' object is not subscriptable`
> 
> The problem is that async_device_info_to_link_from_entity() is deprecated in HA 2026.8 and now returns None.
> 
> A minimal fix is:
> 
>     1. In custom_components/lampie/orchestrator.py, change the import:
> 
> 
> ```
> from homeassistant.helpers.device import (
>     async_device_info_to_link_from_entity,
>     async_entity_id_to_device_id,
> )
> ```
> 
> to:
> 
> ```
> from homeassistant.helpers.device import async_entity_id_to_device_id
> ```
> 
>     2. Around line 895, change:
> 
> 
> ```
> device_info = async_device_info_to_link_from_entity(self._hass, switch_id)
> ```
> 
> to:
> 
> ```
> device_id = async_entity_id_to_device_id(self._hass, switch_id)
> device_info = dr.async_get(self._hass).async_get(device_id) if device_id else None
> ```
> 
>     3. In _zha_service_command(), change:
> 
> 
> ```
> id_tuple = next(iter(device_info["identifiers"]))
> ```
> 
> to:
> 
> ```
> id_tuple = next(iter(device_info.identifiers))
> ```
> 
> The existing `ieee = id_tuple[1]` line remains unchanged.
> 
> This allows Lampie to obtain the DeviceEntry from the entity ID using the current HA API and access its identifiers as attributes rather than using the old DeviceInfo dictionary.

Worked for me as well, Thanks!

**Comment by wuehler** [comment]
Thanks @pkscout / @wbyoung — confirming v0.3.1 fixes the crash this issue was filed for.

Verified on two HA 2026.8 instances (ZHA, Inovelli VZM31-SN), 6 config entries and 33 target
switches between them. Toggling a notification switch now completes cleanly, and debug logging
shows `issued commands to update light.inovelli_* leds: all` across the fleet — that line sits
after the `_zha_service_command` dispatch, so the previously-fatal path is genuinely executing.

That said, I'd suggest **not** closing this issue yet — v0.3.1 fixed the one call site that
crashed, but two related things remain.

### 1. Two call sites still use the deprecated helper

`async_device_info_to_link_from_entity` is still imported and called at:

- `custom_components/lampie/__init__.py:10` / `:94`
- `custom_components/lampie/sensor.py:20` / `:161`

Both are `if device_info is not None`-guarded, so today they only degrade cosmetically —
device-linking is skipped and users get log spam:

```
WARNING [custom_components.lampie.sensor] skipping creation of sensors for
light.inovelli_master_bedside_lamp on <entry> because an associated device could not be found
```

But HA is now emitting the hard deadline itself:

```
WARNING [homeassistant.helpers.frame] Detected that custom integration 'lampie' calls
async_device_info_to_link_from_entity, which is deprecated and always returns None ...
Set entity.device_entry = async_entity_id_to_device(hass, source_entity_id) instead at
custom_components/lampie/__init__.py, line 94 ...
This will stop working in Home Assistant 2027.8.0
```

Since the helper is unconditionally `None` on 2026.8+, those two sites are already dead code in
practice — every user on 2026.8 has silently lost the sensor/device linking. The replacement HA
recommends is `entity.device_entry = async_entity_id_to_device(hass, source_entity_id)`.

### 2. The `None` path is still unguarded (same failure, new exception type)

In `orchestrator.py._issue_switch_commands`:

```python
device_id = async_entity_id_to_device_id(self._hass, switch_id)
device_info = (
    dr.async_get(self._hass).async_get(device_id) if device_id else None
)
```

`device_info` can still be `None` — and it flows unguarded through
`_dispatch_service_command` into `_zha_service_command`, which does:

```python
id_tuple = next(iter(device_info.identifiers))
```

So an entity with no device (or a registry miss) produces
`AttributeError: 'NoneType' object has no attribute 'identifiers'` — the same class of crash as
the original `'NoneType' object is not subscriptable`, just with a different message. The
trigger condition is much rarer now, which is why it isn't showing up in practice, but the
unguarded assumption itself wasn't removed. An early guard that skips + logs (or raises a
`HomeAssistantError` naming the switch) would close it out properly.

### 3. Minor: the type annotations no longer match

`device_info` is annotated `dr.DeviceInfo` at `orchestrator.py:933`, `:954` and `:983`, but
v0.3.1 now passes a `dr.DeviceEntry`. These are quite different — `DeviceInfo` is a `TypedDict`
(so `device_info["identifiers"]`), `DeviceEntry` is a dataclass (so `device_info.identifiers`).
No runtime effect, but it makes the change easy to misread, and it silently breaks anyone
carrying a local patch that built a `DeviceInfo` for the old consumer.

Happy to open these as separate issues if you'd prefer to close this one on the crash fix.

**Comment by wbyoung** [comment]
@wuehler a new issue would be good. You can just create one for all three of the above points. Feel free to open a PR to address it as well if you have time. Thanks for calling this out!
