### PR TITLE
Finish the HA 2026.8 device-linking migration

### LINKED ISSUE #36: Finish the HA 2026.8 migration: 2 remaining deprecated call sites, an unguarded None path, and stale type annotations
### Requirements

- [x] I have updated Lampie to the latest available version.

- [x] I did a search to see if there is a similar issue or if a pull request is open.

### The problem

Follow-up to #34 as requested by @wbyoung. v0.3.1 fixed the call site that crashed; these three
are what's left. Grouping them here since they all stem from the same HA 2026.8 change.

**Environment:** HA 2026.8, Lampie v0.3.1, ZHA + Inovelli VZM31-SN, verified across two
instances (6 config entries, 33 target switches).

## 1. `async_device_info_to_link_from_entity` still called in two places

Still imported and called at:

- `custom_components/lampie/__init__.py:10` / `:94` (`async_cleanup_device_registry`)
- `custom_components/lampie/sensor.py:20` / `:161` (`async_setup_entry`)

On 2026.8+ this helper returns `None` **unconditionally** — it never inspects the device — so
both sites take their `else` branch every time.

**Observed effects:**

- **No Lampie sensors are created at all.** On my larger instance the entity registry contains
  5 `lampie` entities, all `switch`, zero `sensor`. Every `is_primary` switch hits the
  `skipping creation of sensors` branch.
- **~25 warnings per startup** across `skipping creation of sensors` and
  `skipping linking of switch to config entry`, one pair per light per entry.
- In `async_cleanup_device_registry`, `switch_devices` is now always an empty set, so the
  `if item not in switch_devices` guard is always true. In practice nothing is actually
  unlinked — the only devices whose `config_entry_id` points at a Lampie entry are Lampie's own
  service devices, which the `if item[0] == DOMAIN: continue` check skips — so this is inert
  rather than harmful today. But the function no longer does what it was written to do.

**Worth noting for the fix:** in 2026.8 a device carries a single `config_entry_id`, so the old
pattern of adding Lampie's config entry to a ZHA-owned device can't be represented at all. HA's
own deprecation warning names the migration:

```
Set entity.device_entry = async_entity_id_to_device(hass, source_entity_id) instead at
custom_components/lampie/__init__.py, line 94 ...
This will stop working in Home Assistant 2027.8.0
```

**One trap for whoever implements it:** `LampieDistributedEntity.__init__` derives the unique id
from the device identifiers —

```python
id_tuple = next(iter(switch_device_info["identifiers"]))
id_slug = "_".join(id_tuple)
self._attr_unique_id = f"{id_slug}_{description.key}"
```

so a fix has to yield the *same* identifier tuple, or it will silently orphan existing sensor
entities for anyone still on ≤2026.7. (Separately, `next(iter(...))` over a set is
order-dependent if a device ever has more than one identifier — not an issue for ZHA devices,
which have one, but it's load-bearing for the unique id.)

## 2. The `None` path is still unguarded in `orchestrator.py`

```python
device_id = async_entity_id_to_device_id(self._hass, switch_id)
device_info = (
    dr.async_get(self._hass).async_get(device_id) if device_id else None
)
```

`device_info` can still be `None`, and it flows unguarded through `_dispatch_service_command`
into `_zha_service_command`:

```python
id_tuple = next(iter(device_info.identifiers))
```

An entity with no device, or a registry miss, yields
`AttributeError: 'NoneType' object has no attribute 'identifiers'` — the same failure as the
original `'NoneType' object is not subscriptable`, with a different message. Much rarer trigger
now (all 33 of my switches resolve a device id), but the unguarded assumption itself survived
the fix. An early skip-and-log, or a `HomeAssistantError` naming the switch, would close it.

Note `_z2m_service_command` doesn't use `device_info` at all (`# noqa: ARG002`), so this only
affects the ZHA path.

## 3. Type annotations no longer match the value passed

`device_info` is annotated `dr.DeviceInfo` at `orchestrator.py:933`, `:954` and `:983`, but
v0.3.1 now passes a `dr.DeviceEntry`. `DeviceInfo` is a `TypedDict` (`device_info["identifiers"]`),
`DeviceEntry` is a dataclass (`device_info.identifiers`). No runtime effect, but it makes the
v0.3.1 change easy to misread — and it silently breaks anyone carrying a local patch that built a
`DeviceInfo` for the old consumer, which is a real population given how long #34 was open.

### What version of Lampie has the issue?

v0.3.1

### What was the last working version of Lampie?

_No response_

### Diagnostics information

_No response_

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by wuehler**
Fixes #36. (Opening a PR as suggested in #34.)

## The problem

v0.3.1 fixed the call site that crashed, but `async_device_info_to_link_from_entity`
is still called at `__init__.py:94` and `sensor.py:161`. It has returned `None`
**unconditionally** since HA 2026.8, so on current HA:

- **no Lampie sensors are created at all** — the `is_primary` branch always falls through
  to `skipping creation of sensors`
- every startup logs a warning per switch per config entry (~25 on one of my instances)
- HA reports the helper is removed in **2027.8**

## Why the shape of the fix

A device belongs to exactly one config entry as of 2026.8, so the old approach — handing
the entity a `DeviceInfo` carrying the *switch device's* identifiers — can no longer be
represented at all. It isn't a matter of restoring the old linking; the model changed.
HA's replacement is to attach the **entity** to the device instead.

Concretely:

- **`entity.py`** — `LampieDistributedEntity` takes a `DeviceEntry` and sets
  `self.device_entry`. It must also clear `_attr_device_info`: the entity platform prefers
  `device_info` over a pre-set `device_entry`, so leaving the inherited service-device
  `device_info` in place silently re-attaches these entities to the config entry's own
  service device (I hit this — the sensors came back as `sensor.doors_open_*` instead of
  `sensor.kitchen_*`).
- **`sensor.py`** — resolve the switch's device via `async_entity_id_to_device_id` +
  the device registry, and drop the branch that added our config entry to the switch
  device, which is no longer possible.
- **`__init__.py`** — resolve identifiers the same way in `async_cleanup_device_registry`.

**Unique ids are preserved.** They're still derived from the same device identifiers, so
existing sensor entities keep their ids rather than being orphaned. Verified: all **510**
`unique_id`/`entity_id` values across the snapshots are byte-identical before and after.

Also in this PR, per points 2 and 3 of the issue:

- guard the ZHA dispatch when no device resolves, instead of failing with an
  `AttributeError` deeper in the call stack (`_z2m_service_command` doesn't use the
  device, so the guard is ZHA-only)
- correct the `device_info` annotations, which have said `DeviceInfo` since v0.3.1 while
  actually carrying a `DeviceEntry`

## The test pin

`requirements.test.txt` moves to `pytest-homeassistant-custom-component==0.13.355`
(HA 2026.8.1), which drags `pytest` and `syrupy` to the versions it pins.

This isn't incidental — **it's why this shipped**. On the old `0.13.252` pin the suite runs
HA 2025.6.1, where the deprecated helper still works, so none of this is reachable from CI.
For reference, the unmodified tree against HA 2026.8.1 is **91 failed / 103 passed**; with
this PR it's **191 passed / 3 failed**.

The syrupy bump changes how empty sets serialize (`set({})` → `list([])`), so the snapshots
are regenerated. That's the bulk of the diff; the code change is ~70 lines.

## Three pre-existing failures I did *not* fix

Three scenario tests fail, and they fail identically on the **base commit** with the same
dependencies — they are 2026.8 regressions the old pin was hiding, unrelated to device linking:

```
test_scenarios.py::test_single_config_entry[zha-doors_open_multiple_switches_dismissed]
test_scenarios.py::test_dismissal_from_switch[config_double_press_dismiss_higher_priority_updates_to_display_original]
test_scenarios.py::test_dismissal_from_switch[aux_double_press_dismiss_higher_priority_updates_to_display_original]
```

All three are the same symptom: a second LED update is treated as a no-op, so one
`zha.issue_zigbee_cluster_command` is issued where the scenario expects two. I left them
failing rather than `xfail`-ing them, since that would hide a real bug — happy to open a
separate issue, or to mark them if you'd rather have CI green first.

You can confirm the attribution with:

```
git stash && pytest tests/test_scenarios.py -q ; git stash pop
```

## Verification

Beyond the suite: deployed to a live HA 2026.8.3 install (ZHA, Inovelli VZM31-SN). Sensor
count for the config entry went **0 → 15** (5 per switch × 3 switches), each attached to the
correct ZHA device, with no config-entry claiming and no deprecation warnings from the
sensor/init paths.

## This sets a minimum HA version -- 2026.8

Worth calling out explicitly, since it's a distribution decision rather than a code one.

A pre-set `device_entry` is only honoured from 2026.8, where `entity_platform` gained the
`else: device = entity.device_entry` branch. On 2025.6.1 the equivalent code is just:

```python
if self.config_entry and (device_info := entity.device_info):
    device = ...
else:
    device = None
```

So on ≤2026.7 this patch would create the sensors but leave them attached to no device --
no crash, but a silent degradation, and fresh installs would get different entity ids
because `has_entity_name` has no device name to build on.

Since the deprecated helper still works on ≤2026.7, those users are fine on v0.3.1 today.
The honest thing seemed to be to declare the floor rather than quietly degrade them, so
this adds `"homeassistant": "2026.8.0"` to `hacs.json`, which stops HACS offering the
update to anyone who'd be worse off for taking it.

Happy to drop that line if you'd rather keep older HA on the same release, or to
version-gate the behaviour instead -- your call on how you want to support 2026.7 and
earlier.

## Provenance

This was written with Claude (Anthropic), and the commit carries a `Co-Authored-By`
trailer to that effect. Every claim above was checked against a real environment rather
than asserted: the pass/fail counts are actual runs against HA 2026.8.1, the 510 unchanged
identifiers are a diff of the generated snapshots, the older-HA behaviour is read from
2025.6.1's `entity_platform`, and the 0 → 15 sensor result is from a live 2026.8.3 install
with real Inovelli hardware. Please review it as critically as that warrants.

### CODE REVIEW

**Comment by wbyoung** [comment]
I'd like to keep the minimum version below 2026.8, and as mentioned [in #36](https://github.com/wbyoung/lampie/issues/36#issuecomment-5456238690), the changing of pinned dependencies should not be needed.

Eventually, `pytest-homeassistant-custom-component` and this will be tested against 2026.8 (again, I haven't had time to confirm that's what's keeping the HA dependency back, but I suspect that's the case).

I've installed this branch locally & it does appear to resolve the noted issues in 2026.8.

**Comment by wbyoung** [comment]
@wuehler I reverted some of the changes and got everything passing in CI. I also found that the install of `pytest-homeassistant-custom-component` was using an older version, `pytest-homeassistant-custom-component-0.13.316` because of the lower Python 3.13 in use, so updated the test matrix to use 3.14 for the upgraded dependencies so that this is [tested against the latest builds](https://github.com/wbyoung/lampie/actions/runs/33263202456) (which is also showing failures that we can follow up and fix later).

Let me know if these changes seem correct to you & we can get this merged.

**Comment by wuehler** [comment]
Thanks — happy to drop the `hacs.json` floor and the pin change, and the
`suggested_object_id` override is a much better answer to the older-core problem than my
version bound was. Removing the unlink loop outright is also the right call given it can no
longer do anything.

One problem with it though, and I think it needs fixing before this merges.

## The override doubles the device name on 2026.8

From 2026.8 the entity platform honours a pre-set `device_entry` and derives the object id
from the device name itself, so prefixing it again in `suggested_object_id` applies it twice:

```
sensor.kitchen_kitchen_notification
sensor.entryway_entryway_effect_color
sensor.dining_room_dining_room_notification
```

I ran the suite against `homeassistant==2026.8.1` on `009765d` and regenerated the
snapshots: **400 of 400 entity ids gain the duplicated prefix.** `unique_id` is unaffected,
so nothing is orphaned — but the ids themselves are wrong.

This isn't an upgrade edge case, it's the main path. Anyone on 2026.8 today has **no**
Lampie sensors at all — that's the bug being fixed — so the sensors are all created fresh on
upgrade and every one of them lands with the doubled id.

## Why the suite doesn't show it

On the restored pin the tests run HA 2025.6.1, where the platform attaches no device, so the
override supplies the name exactly once and the ids come out correct. The double only
appears on 2026.8.

## Fix

Gate the prefix on whether the running core honours `device_entry`:

```python
_DEVICE_ENTRY_HONOURED = AwesomeVersion(HA_VERSION) >= AwesomeVersion("2026.8.0b0")

@property
def suggested_object_id(self) -> str | None:
    # from 2026.8 the entity platform honours a pre-set `device_entry` and
    # derives the object id from the device name itself; prefixing here too
    # would double it. on older cores the platform sees no device, so the
    # prefix has to come from us.
    if _DEVICE_ENTRY_HONOURED:
        return super().suggested_object_id
    return f"{self.device_entry.name}_{super().suggested_object_id}"
```

With that, the ids generated on 2026.8.1 match your 2025.6.1 snapshots exactly — all **510**
`entity_id`/`unique_id` values identical, no snapshot churn, so it's verifiably correct on
both cores. Suite is 191 passed / 3 failed, those 3 being the pre-existing scenario failures
from point 5 of #36.

Happy to push that to this branch if you'd like it, or leave it to you.

## One note on CI

The matrix change looks right, and the 3.13 → `0.13.316` interaction is a good catch — that
explains the `2026.2.3`.

Just so it's on the record: the `info` job forces `["pinned"]` for `pull_request`, so the leg
that ran here is HA 2025.6.1 and wouldn't cover this either way. A `workflow_dispatch` on the
branch with `upgraded: true` should reproduce it if you'd like to see it directly.

**Comment by wbyoung** [comment]
@wuehler ok, give it another look now. I think (hope) everything should be covered at this point.

**Comment by wuehler** [comment]
Looks right to me — confirmed on both cores.

I ran your `61ee8ed` against `homeassistant==2026.8.1`: **194 passed, 789 snapshots passed,
zero failures**, and regenerating the snapshots produces **no drift at all** — every
`entity_id`/`unique_id` identical. The ids come out correct now:

```
sensor.dining_room_notification
sensor.entryway_effect_color
```

Together with the green `pinned, 3.13` leg on 2025.6.1, that's both sides of the gate
covered.

The `tests/syrupy.py` normalisation is a much better answer than what I'd reached for.
Making the snapshots version-agnostic means one set is valid on both cores, instead of
regenerating them against whichever HA the pin happens to point at — that also removes the
`config_entry_id` volatility I'd papered over with an `exclude` in the diagnostics test.

Good catch on the three scenario failures too. I'd flagged them as pre-existing and hadn't
chased the cause; `standard_switch.device_id` going stale where
`async_entity_id_to_device_id` is needed explains it, and it being a test-side bug rather
than a product one is the better outcome. That closes point 5 of #36.

Two leftovers, both non-blocking — happy for these to be follow-ups or dropped entirely,
just noting them so they're a decision rather than an oversight:

- the ZHA dispatch `None` guard (point 2 of #36) is still out; an entity with no device
  reaches `next(iter(device_info.identifiers))` and raises `AttributeError`. Rare, and I
  don't feel strongly about where it lives.
- `async_cleanup_device_registry` is now just a docstring but is still called from
  `async_setup_entry` — probably worth removing it and the call site together.

Ship it as far as I'm concerned. Thanks for taking this the rest of the way, and for the
patience on the back-and-forth.

**Comment by wbyoung** [comment]
Feel free to followup on those two points, but as stated they're very minor.
