### ISSUE TITLE
Finish the HA 2026.8 migration: 2 remaining deprecated call sites, an unguarded None path, and stale type annotations

### ISSUE THREAD

**Issue by wuehler** [wbyoung/lampie#36]
### Requirements

- [x] I have updated Lampie to the latest available version.

- [x] I did a search to see if there is a similar issue or if a pull request is open.

### The problem

Follow-up to #34 as requested by @wbyoung. v0.3.1 fixed the call site that crashed; these three
are what's left. Grouping them here since they all stem from the same HA 2026.8 change.

**Environment:** HA 2026.8, Lampie v0.3.1, ZHA + Inovelli VZM31-SN, verified across two
instances (6 config entries, 33 target switches).

## 1. `async_device_info_to_link_from_entity` still called in two places

Still imported and called at:

- `custom_components/lampie/__init__.py:10` / `:94` (`async_cleanup_device_registry`)
- `custom_components/lampie/sensor.py:20` / `:161` (`async_setup_entry`)

On 2026.8+ this helper returns `None` **unconditionally** — it never inspects the device — so
both sites take their `else` branch every time.

**Observed effects:**

- **No Lampie sensors are created at all.** On my larger instance the entity registry contains
  5 `lampie` entities, all `switch`, zero `sensor`. Every `is_primary` switch hits the
  `skipping creation of sensors` branch.
- **~25 warnings per startup** across `skipping creation of sensors` and
  `skipping linking of switch to config entry`, one pair per light per entry.
- In `async_cleanup_device_registry`, `switch_devices` is now always an empty set, so the
  `if item not in switch_devices` guard is always true. In practice nothing is actually
  unlinked — the only devices whose `config_entry_id` points at a Lampie entry are Lampie's own
  service devices, which the `if item[0] == DOMAIN: continue` check skips — so this is inert
  rather than harmful today. But the function no longer does what it was written to do.

**Worth noting for the fix:** in 2026.8 a device carries a single `config_entry_id`, so the old
pattern of adding Lampie's config entry to a ZHA-owned device can't be represented at all. HA's
own deprecation warning names the migration:

```
Set entity.device_entry = async_entity_id_to_device(hass, source_entity_id) instead at
custom_components/lampie/__init__.py, line 94 ...
This will stop working in Home Assistant 2027.8.0
```

**One trap for whoever implements it:** `LampieDistributedEntity.__init__` derives the unique id
from the device identifiers —

```python
id_tuple = next(iter(switch_device_info["identifiers"]))
id_slug = "_".join(id_tuple)
self._attr_unique_id = f"{id_slug}_{description.key}"
```

so a fix has to yield the *same* identifier tuple, or it will silently orphan existing sensor
entities for anyone still on ≤2026.7. (Separately, `next(iter(...))` over a set is
order-dependent if a device ever has more than one identifier — not an issue for ZHA devices,
which have one, but it's load-bearing for the unique id.)

## 2. The `None` path is still unguarded in `orchestrator.py`

```python
device_id = async_entity_id_to_device_id(self._hass, switch_id)
device_info = (
    dr.async_get(self._hass).async_get(device_id) if device_id else None
)
```

`device_info` can still be `None`, and it flows unguarded through `_dispatch_service_command`
into `_zha_service_command`:

```python
id_tuple = next(iter(device_info.identifiers))
```

An entity with no device, or a registry miss, yields
`AttributeError: 'NoneType' object has no attribute 'identifiers'` — the same failure as the
original `'NoneType' object is not subscriptable`, with a different message. Much rarer trigger
now (all 33 of my switches resolve a device id), but the unguarded assumption itself survived
the fix. An early skip-and-log, or a `HomeAssistantError` naming the switch, would close it.

Note `_z2m_service_command` doesn't use `device_info` at all (`# noqa: ARG002`), so this only
affects the ZHA path.

## 3. Type annotations no longer match the value passed

`device_info` is annotated `dr.DeviceInfo` at `orchestrator.py:933`, `:954` and `:983`, but
v0.3.1 now passes a `dr.DeviceEntry`. `DeviceInfo` is a `TypedDict` (`device_info["identifiers"]`),
`DeviceEntry` is a dataclass (`device_info.identifiers`). No runtime effect, but it makes the
v0.3.1 change easy to misread — and it silently breaks anyone carrying a local patch that built a
`DeviceInfo` for the old consumer, which is a real population given how long #34 was open.

### What version of Lampie has the issue?

v0.3.1

### Anything in the logs that might be useful for us?

```txt

```

**Comment by wuehler** [comment]
Two more findings, from putting a fix together for the above — adding them here rather than
in the PR so they're on the record independently of it.

## 4. CI can't see any of this — the test pin is HA 2025.6.1

This is arguably the root cause of the whole issue, and it will hide the next one too.

`requirements.test.txt` pins `pytest-homeassistant-custom-component==0.13.252`, which resolves
to **`homeassistant==2025.6.1`**. On that version `async_device_info_to_link_from_entity` still
works normally, so the entire failure mode above is unreachable from CI — the suite is green
while the integration creates no sensors at all on current HA.

For scale, running the current `main` against HA 2026.8.1 instead:

```
91 failed, 103 passed
```

Even setting aside the fix, it's worth moving the pin forward so this class of breakage is
visible before users hit it.

## 5. Three scenario failures unrelated to device linking

Surfaced by that same pin bump, and *not* caused by any fix for the above — they reproduce on
unmodified `main` with only the test dependencies changed:

```
test_scenarios.py::test_single_config_entry[zha-doors_open_multiple_switches_dismissed]
test_scenarios.py::test_dismissal_from_switch[config_double_press_dismiss_higher_priority_updates_to_display_original]
test_scenarios.py::test_dismissal_from_switch[aux_double_press_dismiss_higher_priority_updates_to_display_original]
```

Same symptom in all three: a second LED update is treated as a no-op, so one
`zha.issue_zigbee_cluster_command` is issued where the scenario expects two. I haven't chased
the cause — flagging it separately so it isn't mistaken for fallout from the device-linking work.
Happy to split this into its own issue if you'd prefer.

---

The PR I'm about to open addresses points 1–3 and also moves the test pin (point 4),
since without it none of the fix is exercisable. It will show **red CI** because of the three
failures in point 5 — those are pre-existing, not introduced by it, and I'd rather leave them
visible than `xfail` them. Reproduction for the attribution is in the PR.

**Comment by wbyoung** [comment]
> 4. CI can't see any of this — the test pin is HA 2025.6.1

The nightly CI run removes all pinned dependencies when it runs. But it looks like it installed `homeassistant-2026.2.3`. I'm guessing `pytest-homeassistant-custom-component-0.13.316` specifies this version and that that package just hasn't been updated yet to match (but I didn't check that just now).

Regardless, the dependency should stay pinned to the old version & allow the upgraded CI job to handle testing against the latest version.
